/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myfirstapplication;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author 44789
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        if(jDecimalPlacesTextField.getText().equals("")){
                jDecimalPlacesTextField.setText("0");
            }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     
     // Integer and double validation for the input text field , so that user cannot enter any type of string in there.
    private boolean authenticateInput(){
        try {
                double input1 = Double.valueOf(jInputTextField1.getText());
                double input2 = Double.valueOf(jInputTextField2.getText());
                return true;
        }
        catch (Exception e){
            return false;
        }
    }
    
   

    // A separate method has been created for Data Validation for Dividing two numbers
    private boolean jDivisionDataValidation(double input1, double input2){
        
        boolean dataInvalid = false;
        if (input1 ==0 || input2 == 0 ){
            dataInvalid = true;  
        }
        return dataInvalid;
        
    }
    
    // A separate power method for the implementation of different functions as this method will be used
    // everywhere else.
    private double power(double input1, double input2){
        double result = 1; 
        for (int i = 0; i < input2; i++) {
            result *= input1; 
        }
        return result; 
    }
    
    
     private boolean authenticateDp() {
        try{
            
            int input1 = Integer.valueOf(jDecimalPlacesTextField.getText());
            return true;
        }
        catch (Exception e){
            return false;
        }
    }
     
     
    
    // Round up function 
    private double round(double input1, String decimalPlaces){
        
        
        if (authenticateDp()){
            if (Integer.valueOf(decimalPlaces) > 10 || Integer.valueOf(decimalPlaces) < 0 ){
            JOptionPane.showMessageDialog(this,"Please Check range of DP and answer might not be right,"); 
            }
        
            int decimalplaces = Integer.valueOf(decimalPlaces);
            input1 *= power(10, decimalplaces);
            if (input1 >= 0){
                input1 += 0.5;
            }
            else {
            input1 -= 0.5;
            }
        long intinput1 = (long) input1;
        input1 = intinput1 / (double)power(10,decimalplaces);
        return input1;
    }
        else{
            input1 *= power(10,0);
            if(input1 >= 0){
                input1 += 0.5;
            }
            else {
                input1 -= 0.5;
         
            }
            int intinput1 = (int) input1;
            input1 = intinput1 / (double) power(10,0);
            return input1;
        }
    }
   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalculatorPanel = new javax.swing.JPanel();
        jInputLabel1 = new javax.swing.JLabel();
        jInputTextField1 = new javax.swing.JTextField();
        InputLabel2 = new javax.swing.JLabel();
        jInputTextField2 = new javax.swing.JTextField();
        jOutputLabel3 = new javax.swing.JLabel();
        jOutputTextField = new javax.swing.JTextField();
        jAddButton = new javax.swing.JButton();
        jSubstractButton = new javax.swing.JButton();
        jMultiplyButton = new javax.swing.JButton();
        jDivideButton = new javax.swing.JButton();
        jPowerButton = new javax.swing.JButton();
        jVolumeOfSphereButton = new javax.swing.JButton();
        jVolumeOfCylinderButton = new javax.swing.JButton();
        jSquareBasedPyramidVolButton = new javax.swing.JButton();
        jCloseCalculatorButton = new javax.swing.JButton();
        jDecimalPlacesLabel = new javax.swing.JLabel();
        jDecimalPlacesTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInputLabel1.setText("Input 1");

        jInputTextField1.setText("0.0");

        InputLabel2.setText("Input 2");

        jInputTextField2.setText("0.0");

        jOutputLabel3.setText("Output");

        jOutputTextField.setText("0.0");

        jAddButton.setText("+");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonjSumButtonActionPerformed(evt);
            }
        });

        jSubstractButton.setText("-");
        jSubstractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubstractButtonActionPerformed(evt);
            }
        });

        jMultiplyButton.setText("*");
        jMultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMultiplyButtonActionPerformed(evt);
            }
        });

        jDivideButton.setText("/");
        jDivideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDivideButtonActionPerformed(evt);
            }
        });

        jPowerButton.setText("pow");
        jPowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPowerButtonActionPerformed(evt);
            }
        });

        jVolumeOfSphereButton.setText("Volume Of Sphere");
        jVolumeOfSphereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolumeOfSphereButtonActionPerformed(evt);
            }
        });

        jVolumeOfCylinderButton.setText("Volume Of Cylinder");
        jVolumeOfCylinderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolumeOfCylinderButtonjCylinderVolumeAction(evt);
            }
        });

        jSquareBasedPyramidVolButton.setText("SquareBasedPyramid Volume");
        jSquareBasedPyramidVolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSquareBasedPyramidVolButtonActionPerformed(evt);
            }
        });

        jCloseCalculatorButton.setText("Close Calculator");
        jCloseCalculatorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseCalculatorButtonMouseClicked(evt);
            }
        });

        jDecimalPlacesLabel.setText("Decimal Places");

        jLabel1.setText("Enter from 0 to 10");

        javax.swing.GroupLayout jCalculatorPanelLayout = new javax.swing.GroupLayout(jCalculatorPanel);
        jCalculatorPanel.setLayout(jCalculatorPanelLayout);
        jCalculatorPanelLayout.setHorizontalGroup(
            jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jInputLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(jCloseCalculatorButton))
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDecimalPlacesLabel)
                            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                .addComponent(jDecimalPlacesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(InputLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jOutputLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(64, 64, 64)
                                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jInputTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCalculatorPanelLayout.createSequentialGroup()
                                                .addComponent(jPowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                                .addComponent(jAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49)))
                                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSubstractButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jVolumeOfCylinderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jVolumeOfSphereButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                                .addComponent(jMultiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jDivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jSquareBasedPyramidVolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(670, Short.MAX_VALUE))
        );
        jCalculatorPanelLayout.setVerticalGroup(
            jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCalculatorPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jInputLabel1)
                            .addComponent(jInputTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCloseCalculatorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputLabel2)
                    .addComponent(jInputTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOutputLabel3)
                    .addComponent(jOutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddButton)
                    .addComponent(jSubstractButton)
                    .addComponent(jMultiplyButton)
                    .addComponent(jDivideButton))
                .addGap(18, 18, 18)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPowerButton)
                    .addComponent(jVolumeOfCylinderButton)
                    .addComponent(jVolumeOfSphereButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDecimalPlacesLabel)
                .addGap(10, 10, 10)
                .addGroup(jCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSquareBasedPyramidVolButton)
                    .addComponent(jDecimalPlacesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jCalculatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jCalculatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddButtonjSumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonjSumButtonActionPerformed
        // TODO add your handling code here:
        if(authenticateInput()){
            double input1 = Double.valueOf(jInputTextField1.getText());
            double input2 = Double.valueOf(jInputTextField2.getText());

            double output = input1+ input2;

            jOutputTextField.setText(String.valueOf(round(output, jDecimalPlacesTextField.getText())));
        }
        else{
            jOutputTextField.setText("String Detected in Input field");
        }
    }//GEN-LAST:event_jAddButtonjSumButtonActionPerformed

    private void jSubstractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubstractButtonActionPerformed
        // TODO add your handling code here:
        if(authenticateInput()){
            double input1 = Double.valueOf(jInputTextField1.getText());
            double input2 = Double.valueOf(jInputTextField2.getText());

            double output = input1 - input2;

            jOutputTextField.setText(String.valueOf(round(output, jDecimalPlacesTextField.getText())));
        }
        else{
            jOutputTextField.setText("String Detected in Input field");
        }
    }//GEN-LAST:event_jSubstractButtonActionPerformed

    private void jMultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMultiplyButtonActionPerformed
        // TODO add your handling code here:
        if(authenticateInput()){
            double input1 = Double.valueOf(jInputTextField1.getText());
            double input2 = Double.valueOf(jInputTextField2.getText());

            double output = input1 * input2;
            jOutputTextField.setText(String.valueOf(round(output, jDecimalPlacesTextField.getText())));

        }
        else{
            jOutputTextField.setText("String Detected in Input field");
        }
    }//GEN-LAST:event_jMultiplyButtonActionPerformed

    private void jDivideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDivideButtonActionPerformed
        if(authenticateInput()){
            double input1 = Double.valueOf(jInputTextField1.getText());
            double input2 = Double.valueOf(jInputTextField2.getText());

            // As one can observe an external function to validate the data provided by the user.
            if (jDivisionDataValidation(input1, input2) ) {
                jOutputTextField.setText("Division by Zero not possible");
            }

            else{
                double output = input1 / input2;
                jOutputTextField.setText(String.valueOf(round(output, jDecimalPlacesTextField.getText())));
                // Here the output has been rounded up by using the string.format to four decimal places.
            }
        }
        else{
            jOutputTextField.setText("String Detected in Input field");
        }

    }//GEN-LAST:event_jDivideButtonActionPerformed

    private void jPowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPowerButtonActionPerformed
        if(authenticateInput()){
            double input1 = Double.valueOf(jInputTextField1.getText());
            double input2 = Double.valueOf(jInputTextField2.getText());

            double output = power(input1,  input2);

            jOutputTextField.setText(String.valueOf(round(output, jDecimalPlacesTextField.getText())));
        }
        else{
            jOutputTextField.setText("String Detected in Input field");
        }
    }//GEN-LAST:event_jPowerButtonActionPerformed

    private void jVolumeOfSphereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolumeOfSphereButtonActionPerformed
        if(authenticateInput()){
            double input1 = Double.valueOf(jInputTextField1.getText());
            double input2 = Double.valueOf(jInputTextField2.getText());

            double output = ((4.0/3.0) * (22.0/7.0) * power(input1,3) );

            // Rouding the floating points upto 4 decimal places to improve presentation of the calculator.
            jOutputTextField.setText(String.valueOf(round(output, jDecimalPlacesTextField.getText())));
        }
        else{
            jOutputTextField.setText("String Detected in Input field");
        }
    }//GEN-LAST:event_jVolumeOfSphereButtonActionPerformed

    private void jVolumeOfCylinderButtonjCylinderVolumeAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolumeOfCylinderButtonjCylinderVolumeAction
        if(authenticateInput()){
            double input1 = Double.valueOf(jInputTextField1.getText());
            double input2 = Double.valueOf(jInputTextField2.getText());

            double output = ((22.0/7.0) * power(input1,2) * input2 );

            // Again rounding up the floating points upto 4 decimal places to improve presentation of the calculator.
            jOutputTextField.setText(String.valueOf(round(output, jDecimalPlacesTextField.getText())));
        }
        else{
            jOutputTextField.setText("String Detected in Input field");
        }
    }//GEN-LAST:event_jVolumeOfCylinderButtonjCylinderVolumeAction

    private void jSquareBasedPyramidVolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSquareBasedPyramidVolButtonActionPerformed
        if(authenticateInput()){
            double input1 = Double.valueOf(jInputTextField1.getText());
            double input2 = Double.valueOf(jInputTextField2.getText());

            double output = (power(input1,2)* (input2/3) );

            // RoundingDoub the floating points upto 4 decimal places to improve presentation of the calculator.
            jOutputTextField.setText(String.valueOf(round(output, jDecimalPlacesTextField.getText())));
        }
        else{
            jOutputTextField.setText("String Detected in Input field");
        }
    }//GEN-LAST:event_jSquareBasedPyramidVolButtonActionPerformed

    private void jCloseCalculatorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseCalculatorButtonMouseClicked
        // TODO add your handling code here:
        MainJFrame obj = new MainJFrame();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jCloseCalculatorButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InputLabel2;
    private javax.swing.JButton jAddButton;
    private javax.swing.JPanel jCalculatorPanel;
    private javax.swing.JButton jCloseCalculatorButton;
    private javax.swing.JLabel jDecimalPlacesLabel;
    private javax.swing.JTextField jDecimalPlacesTextField;
    private javax.swing.JButton jDivideButton;
    private javax.swing.JLabel jInputLabel1;
    private javax.swing.JTextField jInputTextField1;
    private javax.swing.JTextField jInputTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jMultiplyButton;
    private javax.swing.JLabel jOutputLabel3;
    private javax.swing.JTextField jOutputTextField;
    private javax.swing.JButton jPowerButton;
    private javax.swing.JButton jSquareBasedPyramidVolButton;
    private javax.swing.JButton jSubstractButton;
    private javax.swing.JButton jVolumeOfCylinderButton;
    private javax.swing.JButton jVolumeOfSphereButton;
    // End of variables declaration//GEN-END:variables
}
